export default {
  U18G: {
    name: 'Under 18 Girls',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '02780859',
        initials: 'DR',
        lastName: 'Robertson',
        firstName: 'Darcy',
        gender: 'Female',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '02921592',
        initials: 'CA',
        lastName: 'Adams',
        firstName: 'Charli',
        gender: 'Female',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03226921',
        initials: 'JA',
        lastName: 'Asaad',
        firstName: 'Julia',
        gender: 'Female',
        lastTransactionDate: '2019-04-05',
      },
      {
        footyWebNumber: '02921605',
        initials: 'EB',
        lastName: 'Barlow',
        firstName: 'Elise',
        gender: 'Female',
        lastTransactionDate: '2019-03-28',
      },
      {
        footyWebNumber: '03081904',
        initials: 'CB',
        lastName: 'Blasius',
        firstName: 'Chloe',
        gender: 'Female',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '02939863',
        initials: 'ECT',
        lastName: 'Cathro-Turner',
        firstName: 'Emily',
        gender: 'Female',
        lastTransactionDate: '2019-03-28',
      },
      {
        footyWebNumber: '03561798',
        initials: 'IDL',
        lastName: 'De Losa',
        firstName: 'Isabella',
        gender: 'Female',
        lastTransactionDate: '2019-03-26',
      },
      {
        footyWebNumber: '03298371',
        initials: 'JFD',
        lastName: 'Foster-Davies',
        firstName: 'Jaslyn',
        gender: 'Female',
        lastTransactionDate: '2019-04-04',
      },
      {
        footyWebNumber: '03315884',
        initials: 'CGP',
        lastName: 'Gunton-Pincombe',
        firstName: 'Chya',
        gender: 'Female',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03564476',
        initials: 'SM',
        lastName: 'Maloney',
        firstName: 'Sienna',
        gender: 'Female',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '00978618',
        initials: 'AM',
        lastName: 'Martin',
        firstName: 'Alanna',
        gender: 'Female',
        lastTransactionDate: '2020-02-28',
      },
      {
        footyWebNumber: '03319307',
        initials: 'RM',
        lastName: 'Mcmanus',
        firstName: 'Rhian',
        gender: 'Female',
        lastTransactionDate: '2019-02-25',
      },
      {
        footyWebNumber: '02696729',
        initials: 'CP',
        lastName: 'Peterson',
        firstName: 'Chenoa',
        gender: 'Female',
        lastTransactionDate: '2019-02-16',
      },
      {
        footyWebNumber: '01283445',
        initials: 'JP',
        lastName: 'Pottenger',
        firstName: 'Jordan',
        gender: 'Female',
        lastTransactionDate: '2019-04-06',
      },
      {
        footyWebNumber: '02841746',
        initials: 'EP',
        lastName: 'Prior',
        firstName: 'Emily',
        gender: 'Female',
        lastTransactionDate: '2019-03-26',
      },
      {
        footyWebNumber: '03867328',
        initials: 'LT',
        lastName: 'Turin',
        firstName: 'Louizana',
        gender: 'Female',
        lastTransactionDate: '2019-11-02',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '03116190',
        initials: 'PD',
        lastName: 'Deane',
        firstName: 'Paige',
        gender: 'Female',
        club: 'Norwood',
        lastTransferDate: '2017-11-27',
      },
      {
        footyWebNumber: '03227856',
        initials: 'AG',
        lastName: 'Gray',
        firstName: 'Angel',
        gender: 'Female',
        club: 'Boronia',
        lastTransferDate: '2019-02-01',
      },
      {
        footyWebNumber: '02302183',
        initials: 'ZL',
        lastName: 'Lynch',
        firstName: 'Zoe',
        gender: 'Female',
        club: 'Knox',
        lastTransferDate: '2017-03-30',
      },
      {
        footyWebNumber: '03115582',
        initials: 'NM',
        lastName: 'Monyjiek',
        firstName: 'Nyawech',
        gender: 'Female',
        club: 'East Ringwood',
        lastTransferDate: '2018-04-07',
      },
      {
        footyWebNumber: '02728111',
        initials: 'AP',
        lastName: 'Petropoulos',
        firstName: 'Alex',
        gender: 'Female',
        club: 'East Ringwood',
        lastTransferDate: '2018-03-08',
      },
      {
        footyWebNumber: '02841749',
        initials: 'BR',
        lastName: 'Reid',
        firstName: 'Bailey',
        gender: 'Female',
        club: 'Mount Evelyn',
        lastTransferDate: '2018-03-08',
      },
      {
        footyWebNumber: '02960615',
        initials: 'MR',
        lastName: 'Rowlands',
        firstName: 'Merryn',
        gender: 'Female',
        club: 'Kilsyth',
        lastTransferDate: '2017-04-18',
      },
      {
        footyWebNumber: '03143144',
        initials: 'KW',
        lastName: 'Wilkins',
        firstName: 'Kayla',
        gender: 'Female',
        club: 'Kilsyth',
        lastTransferDate: '2019-05-02',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '02453895',
        initials: 'AA',
        lastName: 'Asche',
        firstName: 'Aliesha',
        gender: 'Female',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '03337454',
        initials: 'AB',
        lastName: 'Barton',
        firstName: 'Amber',
        gender: 'Female',
        lastTransactionDate: '2018-05-15',
      },
      {
        footyWebNumber: '02326407',
        initials: 'MB',
        lastName: 'Bellingham',
        firstName: 'Montana',
        gender: 'Female',
        lastTransactionDate: '2015-04-29',
      },
      {
        footyWebNumber: '03127859',
        initials: 'MB',
        lastName: 'Butler',
        firstName: 'Melissa',
        gender: 'Female',
        lastTransactionDate: '2017-04-30',
      },
      {
        footyWebNumber: '03298293',
        initials: 'JD',
        lastName: 'Dornbierer',
        firstName: 'Jacquiline',
        gender: 'Female',
        lastTransactionDate: '2018-04-14',
      },
      {
        footyWebNumber: '02453886',
        initials: 'BE',
        lastName: 'Elliott',
        firstName: 'Brooke',
        gender: 'Female',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '03143522',
        initials: 'JFD',
        lastName: 'Foster-davies',
        firstName: 'Jaslyn',
        gender: 'Female',
        lastTransactionDate: '2017-05-11',
      },
      {
        footyWebNumber: '03114280',
        initials: 'AH',
        lastName: 'Hager',
        firstName: 'Anne',
        gender: 'Female',
        lastTransactionDate: '2017-04-21',
      },
      {
        footyWebNumber: '02519779',
        initials: 'AHW',
        lastName: 'Harris-Wright',
        firstName: 'Alisha',
        gender: 'Female',
        lastTransactionDate: '2015-05-07',
      },
      {
        footyWebNumber: '02902082',
        initials: 'TH',
        lastName: 'Harrison',
        firstName: 'Taniesha',
        gender: 'Female',
        lastTransactionDate: '2016-04-14',
      },
      {
        footyWebNumber: '03114649',
        initials: 'EH',
        lastName: 'Hastas',
        firstName: 'Emma',
        gender: 'Female',
        lastTransactionDate: '2018-02-18',
      },
      {
        footyWebNumber: '03298275',
        initials: 'LH',
        lastName: 'Huntington',
        firstName: 'Liana',
        gender: 'Female',
        lastTransactionDate: '2018-04-14',
      },
      {
        footyWebNumber: '02966475',
        initials: 'AJ',
        lastName: 'Jackson',
        firstName: 'Alayah',
        gender: 'Female',
        lastTransactionDate: '2016-06-23',
      },
      {
        footyWebNumber: '02242702',
        initials: 'LK',
        lastName: 'Kudeweh',
        firstName: 'Lily',
        gender: 'Female',
        lastTransactionDate: '2015-05-09',
      },
      {
        footyWebNumber: '02934639',
        initials: 'JO',
        lastName: "O'Brien",
        firstName: 'Jade',
        gender: 'Female',
        lastTransactionDate: '2018-04-28',
      },
      {
        footyWebNumber: '03256636',
        initials: 'KSW',
        lastName: 'Saffron-Wilkins',
        firstName: 'Kayla',
        gender: 'Female',
        lastTransactionDate: '2018-03-16',
      },
      {
        footyWebNumber: '02345502',
        initials: 'PS',
        lastName: 'Smith',
        firstName: 'Paisley',
        gender: 'Female',
        lastTransactionDate: '2015-05-07',
      },
    ],
  },
  'U17B-GOLD': {
    name: 'Under 17 Boys (Gold)',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '01293769',
        initials: 'AD',
        lastName: 'Derham',
        firstName: 'Andrew',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02070149',
        initials: 'MH',
        lastName: 'Higgins',
        firstName: 'Matthew',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '01852931',
        initials: 'KN',
        lastName: 'Nye',
        firstName: 'Kayden',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03972330',
        initials: 'JP',
        lastName: 'Peters',
        firstName: 'Jamie',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '01306270',
        initials: 'SP',
        lastName: 'Phillips',
        firstName: 'Sean',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02698729',
        initials: 'LR',
        lastName: 'Roberts',
        firstName: 'Liam',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '01292196',
        initials: 'JS',
        lastName: 'Sales',
        firstName: 'Joel',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '01857410',
        initials: 'JVDL',
        lastName: 'Van Der Linden',
        firstName: 'James',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '02263883',
        initials: 'BA',
        lastName: 'Alexander',
        firstName: 'Brayden',
        gender: 'Male',
        lastTransactionDate: '2019-06-29',
      },
      {
        footyWebNumber: '02346009',
        initials: 'LA',
        lastName: 'Amey',
        firstName: 'Lachlan',
        gender: 'Male',
        lastTransactionDate: '2020-02-13',
      },
      {
        footyWebNumber: '01635651',
        initials: 'JB',
        lastName: 'Bright',
        firstName: 'Jacob',
        gender: 'Male',
        lastTransactionDate: '2019-11-21',
      },
      {
        footyWebNumber: '01627488',
        initials: 'BC',
        lastName: 'Calcraft',
        firstName: 'Benjamin',
        gender: 'Male',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '01852149',
        initials: 'DC',
        lastName: 'Christensen',
        firstName: 'Dylan',
        gender: 'Male',
        lastTransactionDate: '2019-05-29',
      },
      {
        footyWebNumber: '02289876',
        initials: 'CG',
        lastName: 'Gerada',
        firstName: 'Corey',
        gender: 'Male',
        lastTransactionDate: '2019-04-04',
      },
      {
        footyWebNumber: '03081082',
        initials: 'SJ',
        lastName: 'Jordy',
        firstName: 'Stafford',
        gender: 'Male',
        lastTransactionDate: '2020-07-02',
      },
      {
        footyWebNumber: '02258097',
        initials: 'JL',
        lastName: 'Lalor',
        firstName: 'Joshua',
        gender: 'Male',
        lastTransactionDate: '2019-12-05',
      },
      {
        footyWebNumber: '02035234',
        initials: 'XL',
        lastName: 'Lech',
        firstName: 'Xavier',
        gender: 'Male',
        lastTransactionDate: '2020-06-29',
      },
      {
        footyWebNumber: '01837285',
        initials: 'RM',
        lastName: 'Martinus',
        firstName: 'Romesh',
        gender: 'Male',
        lastTransactionDate: '2019-03-18',
      },
      {
        footyWebNumber: '01602981',
        initials: 'NM',
        lastName: 'Mason',
        firstName: 'Nicholas',
        gender: 'Male',
        lastTransactionDate: '2020-03-13',
      },
      {
        footyWebNumber: '04027015',
        initials: 'JM',
        lastName: 'Materia',
        firstName: 'Jeremy',
        gender: 'Male',
        lastTransactionDate: '2020-06-15',
      },
      {
        footyWebNumber: '03874725',
        initials: 'SM',
        lastName: 'Moulden',
        firstName: 'Sam',
        gender: 'Male',
        lastTransactionDate: '2019-11-22',
      },
      {
        footyWebNumber: '03511199',
        initials: 'WP',
        lastName: 'Paterson',
        firstName: 'William',
        gender: 'Male',
        lastTransactionDate: '2019-11-18',
      },
      {
        footyWebNumber: '01753854',
        initials: 'DS',
        lastName: 'Stephen',
        firstName: 'Darcy',
        gender: 'Male',
        lastTransactionDate: '2019-11-19',
      },
      {
        footyWebNumber: '02900852',
        initials: 'MS',
        lastName: 'Szeicz',
        firstName: 'Maximilian',
        gender: 'Male',
        lastTransactionDate: '2020-07-01',
      },
      {
        footyWebNumber: '02023786',
        initials: 'BV',
        lastName: 'Vail',
        firstName: 'Benjamin',
        gender: 'Male',
        lastTransactionDate: '2020-06-29',
      },
      {
        footyWebNumber: '01391957',
        initials: 'JW',
        lastName: 'Waterworth',
        firstName: 'Joshua',
        gender: 'Male',
        lastTransactionDate: '2019-03-25',
      },
      {
        footyWebNumber: '01603036',
        initials: 'CW',
        lastName: 'Williams',
        firstName: 'Caleb',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '02090741',
        initials: 'TB',
        lastName: 'Byers',
        firstName: 'Tyson',
        gender: 'Male',
        club: 'Ferntree Gully',
        lastTransferDate: '2019-03-23',
      },
      {
        footyWebNumber: '02463394',
        initials: 'BG',
        lastName: 'Glenn',
        firstName: 'Bailey',
        gender: 'Male',
        club: 'Ferntree Gully',
        lastTransferDate: '2017-05-27',
      },
      {
        footyWebNumber: '01838920',
        initials: 'LG',
        lastName: 'Gordon',
        firstName: 'Levi',
        gender: 'Male',
        club: 'Kilsyth',
        lastTransferDate: '2018-11-05',
      },
      {
        footyWebNumber: '01246019',
        initials: 'MH',
        lastName: 'Helleren',
        firstName: 'Mason',
        gender: 'Male',
        club: 'South Croydon',
        lastTransferDate: '2013-04-12',
      },
      {
        footyWebNumber: '01693628',
        initials: 'CJ',
        lastName: 'Jennings',
        firstName: 'Cody',
        gender: 'Male',
        club: 'Wantirna South',
        lastTransferDate: '2017-02-19',
      },
      {
        footyWebNumber: '02231662',
        initials: 'WL',
        lastName: 'Lach',
        firstName: 'William',
        gender: 'Male',
        club: 'Knox',
        lastTransferDate: '2018-05-04',
      },
      {
        footyWebNumber: '01599880',
        initials: 'LN',
        lastName: 'Newey',
        firstName: 'Lachlan',
        gender: 'Male',
        club: 'Rowville Hawks',
        lastTransferDate: '2017-06-17',
      },
      {
        footyWebNumber: '01266869',
        initials: 'AR',
        lastName: 'Robinson',
        firstName: 'Ashton',
        gender: 'Male',
        club: 'Rowville Hawks',
        lastTransferDate: '2017-06-17',
      },
      {
        footyWebNumber: '01646973',
        initials: 'EVDB',
        lastName: 'Van Den Broek',
        firstName: 'Ethan',
        gender: 'Male',
        club: 'Ferntree Gully',
        lastTransferDate: '2017-05-27',
      },
      {
        footyWebNumber: '01534993',
        initials: 'AW',
        lastName: 'Wild',
        firstName: 'Aiden',
        gender: 'Male',
        club: 'East Ringwood',
        lastTransferDate: '2019-04-04',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '01561882',
        initials: 'DB',
        lastName: 'Bannan',
        firstName: 'Daniel',
        gender: 'Male',
        lastTransactionDate: '2015-12-30',
      },
      {
        footyWebNumber: '02058774',
        initials: 'TB',
        lastName: 'Bellingham',
        firstName: 'Tait',
        gender: 'Male',
        lastTransactionDate: '2014-03-18',
      },
      {
        footyWebNumber: '02819220',
        initials: 'DD',
        lastName: 'Dewar',
        firstName: 'Daniel',
        gender: 'Male',
        lastTransactionDate: '2017-11-12',
      },
      {
        footyWebNumber: '03079763',
        initials: 'SD',
        lastName: 'Downie',
        firstName: 'Samuel',
        gender: 'Male',
        lastTransactionDate: '2017-11-12',
      },
      {
        footyWebNumber: '03086371',
        initials: 'MH',
        lastName: 'Higgins',
        firstName: 'Matthew',
        gender: 'Male',
        lastTransactionDate: '2017-03-31',
      },
      {
        footyWebNumber: '02497896',
        initials: 'BK',
        lastName: 'Kordatou',
        firstName: 'Bill',
        gender: 'Male',
        lastTransactionDate: '2015-04-10',
      },
      {
        footyWebNumber: '01610264',
        initials: 'JM',
        lastName: 'Morris',
        firstName: 'Jack',
        gender: 'Male',
        lastTransactionDate: '2013-04-20',
      },
      {
        footyWebNumber: '02675740',
        initials: 'JM',
        lastName: 'Morris',
        firstName: 'Jacob',
        gender: 'Male',
        lastTransactionDate: '2018-04-05',
      },
      {
        footyWebNumber: '02234531',
        initials: 'BN',
        lastName: 'Nelsson',
        firstName: 'Brandon',
        gender: 'Male',
        lastTransactionDate: '2016-04-12',
      },
      {
        footyWebNumber: '02728107',
        initials: 'NP',
        lastName: 'Petropoulos',
        firstName: 'Nick',
        gender: 'Male',
        lastTransactionDate: '2016-04-08',
      },
      {
        footyWebNumber: '01561129',
        initials: 'BR',
        lastName: 'Robb',
        firstName: 'Brandon',
        gender: 'Male',
        lastTransactionDate: '2016-04-12',
      },
      {
        footyWebNumber: '01311988',
        initials: 'LS',
        lastName: 'Schmidtke',
        firstName: 'Liam',
        gender: 'Male',
        lastTransactionDate: '2013-04-09',
      },
      {
        footyWebNumber: '02286120',
        initials: 'RW',
        lastName: 'Wiseman',
        firstName: 'Ryan',
        gender: 'Male',
        lastTransactionDate: '2018-04-02',
      },
    ],
  },
  'U17B-GREEN': {
    name: 'Under 17 Boys (Green)',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '02949384',
        initials: 'JH',
        lastName: 'Higgins',
        firstName: 'Joshua',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '01843424',
        initials: 'CM',
        lastName: 'McGuire',
        firstName: 'Cooper',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03680520',
        initials: 'JA',
        lastName: 'Akanoa',
        firstName: 'Jayden-Rae',
        gender: 'Male',
        lastTransactionDate: '2019-04-28',
      },
      {
        footyWebNumber: '03737182',
        initials: 'LA',
        lastName: 'Akanoa',
        firstName: 'Lorenzo',
        gender: 'Male',
        lastTransactionDate: '2019-05-17',
      },
      {
        footyWebNumber: '02445097',
        initials: 'AAW',
        lastName: 'Aulsebrook-Walker',
        firstName: 'Aaron',
        gender: 'Male',
        lastTransactionDate: '2019-11-14',
      },
      {
        footyWebNumber: '02048274',
        initials: 'LB',
        lastName: 'Bannan',
        firstName: 'Lachlan',
        gender: 'Male',
        lastTransactionDate: '2020-03-10',
      },
      {
        footyWebNumber: '02119149',
        initials: 'CB',
        lastName: 'Bemelmans',
        firstName: 'Carter',
        gender: 'Male',
        lastTransactionDate: '2020-02-18',
      },
      {
        footyWebNumber: '02091636',
        initials: 'PB',
        lastName: 'Blake',
        firstName: 'Phoenix',
        gender: 'Male',
        lastTransactionDate: '2020-06-24',
      },
      {
        footyWebNumber: '01609456',
        initials: 'AD',
        lastName: 'Delbridge',
        firstName: 'Anthony',
        gender: 'Male',
        lastTransactionDate: '2019-11-01',
      },
      {
        footyWebNumber: '02639289',
        initials: 'JG',
        lastName: 'Glenn',
        firstName: 'Jack',
        gender: 'Male',
        lastTransactionDate: '2019-02-17',
      },
      {
        footyWebNumber: '01852131',
        initials: 'AG',
        lastName: 'Green',
        firstName: 'Aaron',
        gender: 'Male',
        lastTransactionDate: '2020-03-01',
      },
      {
        footyWebNumber: '01601097',
        initials: 'RH',
        lastName: 'Heenan',
        firstName: 'Ryan',
        gender: 'Male',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '01865142',
        initials: 'MH',
        lastName: 'Humphreys',
        firstName: 'Max',
        gender: 'Male',
        lastTransactionDate: '2019-11-22',
      },
      {
        footyWebNumber: '01610634',
        initials: 'AK',
        lastName: 'Kane',
        firstName: 'Alex',
        gender: 'Male',
        lastTransactionDate: '2020-07-02',
      },
      {
        footyWebNumber: '02052372',
        initials: 'JM',
        lastName: 'Mainenti',
        firstName: 'Jag',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '02256250',
        initials: 'JM',
        lastName: 'Maxwell',
        firstName: 'Jayden',
        gender: 'Male',
        lastTransactionDate: '2020-06-20',
      },
      {
        footyWebNumber: '02362656',
        initials: 'CO',
        lastName: 'Obrien',
        firstName: 'Charlie',
        gender: 'Male',
        lastTransactionDate: '2020-03-10',
      },
      {
        footyWebNumber: '01532964',
        initials: 'BP',
        lastName: 'Priems',
        firstName: 'Blair',
        gender: 'Male',
        lastTransactionDate: '2019-11-12',
      },
      {
        footyWebNumber: '02022886',
        initials: 'FS',
        lastName: 'Sales',
        firstName: 'Fletcher',
        gender: 'Male',
        lastTransactionDate: '2019-02-22',
      },
      {
        footyWebNumber: '02230377',
        initials: 'WS',
        lastName: 'Scripps',
        firstName: 'William',
        gender: 'Male',
        lastTransactionDate: '2020-03-10',
      },
      {
        footyWebNumber: '01801039',
        initials: 'KS',
        lastName: 'Smith',
        firstName: 'Kane',
        gender: 'Male',
        lastTransactionDate: '2020-03-05',
      },
      {
        footyWebNumber: '01562044',
        initials: 'JS',
        lastName: 'Stallworthy',
        firstName: 'Jaylen',
        gender: 'Male',
        lastTransactionDate: '2020-03-12',
      },
      {
        footyWebNumber: '02331416',
        initials: 'DT',
        lastName: 'Talent',
        firstName: 'Dylan',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02141010',
        initials: 'KT',
        lastName: 'Treverton',
        firstName: 'Kodi',
        gender: 'Male',
        lastTransactionDate: '2019-03-27',
      },
      {
        footyWebNumber: '02275648',
        initials: 'SV',
        lastName: 'Vines',
        firstName: 'Sam',
        gender: 'Male',
        lastTransactionDate: '2020-07-04',
      },
      {
        footyWebNumber: '01863250',
        initials: 'BW',
        lastName: 'White',
        firstName: 'Brandon',
        gender: 'Male',
        lastTransactionDate: '2019-04-01',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '02503773',
        initials: 'RA',
        lastName: 'Ali',
        firstName: 'Rod',
        gender: 'Male',
        club: 'East Ringwood',
        lastTransferDate: '2016-04-08',
      },
      {
        footyWebNumber: '02439956',
        initials: 'TC',
        lastName: 'Clark',
        firstName: 'Tyler',
        gender: 'Male',
        club: 'Kilsyth',
        lastTransferDate: '2018-05-30',
      },
      {
        footyWebNumber: '01596672',
        initials: 'TE',
        lastName: 'Elvin',
        firstName: 'Thomas',
        gender: 'Male',
        club: 'Mooroolbark',
        lastTransferDate: '2019-04-22',
      },
      {
        footyWebNumber: '01810882',
        initials: 'TF',
        lastName: 'Ferguson',
        firstName: 'Thomas',
        gender: 'Male',
        club: 'The Basin',
        lastTransferDate: '2020-06-30',
      },
      {
        footyWebNumber: '01885240',
        initials: 'BG',
        lastName: 'Gale',
        firstName: 'Brayden',
        gender: 'Male',
        club: 'Ferntree Gully',
        lastTransferDate: '2017-03-30',
      },
      {
        footyWebNumber: '02761783',
        initials: 'LJ',
        lastName: 'Jackson',
        firstName: 'Leon',
        gender: 'Male',
        club: 'Rowville Knights',
        lastTransferDate: '2018-05-05',
      },
      {
        footyWebNumber: '02216545',
        initials: 'ML',
        lastName: 'Lill',
        firstName: 'Maddick',
        gender: 'Male',
        club: 'South Croydon',
        lastTransferDate: '2019-02-24',
      },
      {
        footyWebNumber: '02241904',
        initials: 'SL',
        lastName: 'Luedtke',
        firstName: 'Sven',
        gender: 'Male',
        club: 'Wantirna South',
        lastTransferDate: '2020-02-23',
      },
      {
        footyWebNumber: '02640227',
        initials: 'IS',
        lastName: 'Stepanov',
        firstName: 'Igor',
        gender: 'Male',
        club: 'Heathmont',
        lastTransferDate: '2015-04-08',
      },
      {
        footyWebNumber: '02230365',
        initials: 'JW',
        lastName: 'Whitty',
        firstName: 'Jack',
        gender: 'Male',
        club: 'East Ringwood',
        lastTransferDate: '2013-05-03',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '03115980',
        initials: 'MB',
        lastName: 'Bellingham',
        firstName: 'Myelz',
        gender: 'Male',
        lastTransactionDate: '2017-04-22',
      },
      {
        footyWebNumber: '01879008',
        initials: 'NB',
        lastName: 'Boehl',
        firstName: 'Noah',
        gender: 'Male',
        lastTransactionDate: '2017-11-10',
      },
      {
        footyWebNumber: '01569577',
        initials: 'LB',
        lastName: 'Brown',
        firstName: 'Lachlan',
        gender: 'Male',
        lastTransactionDate: '2013-03-10',
      },
      {
        footyWebNumber: '02925917',
        initials: 'BD',
        lastName: 'Decelis',
        firstName: 'Brodie',
        gender: 'Male',
        lastTransactionDate: '2018-04-12',
      },
      {
        footyWebNumber: '02463886',
        initials: 'JD',
        lastName: 'Dooley',
        firstName: 'Jesse',
        gender: 'Male',
        lastTransactionDate: '2018-02-18',
      },
      {
        footyWebNumber: '03072504',
        initials: 'AI',
        lastName: 'Isidro',
        firstName: 'Angelo',
        gender: 'Male',
        lastTransactionDate: '2017-03-23',
      },
      {
        footyWebNumber: '02841920',
        initials: 'TK',
        lastName: 'Kloot',
        firstName: 'Toby',
        gender: 'Male',
        lastTransactionDate: '2016-04-09',
      },
      {
        footyWebNumber: '02051851',
        initials: 'ML',
        lastName: 'Lewis',
        firstName: 'Matthew',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '02900877',
        initials: 'TL',
        lastName: 'Lewis',
        firstName: 'Thomas',
        gender: 'Male',
        lastTransactionDate: '2016-04-08',
      },
      {
        footyWebNumber: '01925787',
        initials: 'BM',
        lastName: 'MacLeod',
        firstName: 'Brayden',
        gender: 'Male',
        lastTransactionDate: '2016-04-09',
      },
      {
        footyWebNumber: '02511863',
        initials: 'JM',
        lastName: 'Majok',
        firstName: 'Jou',
        gender: 'Male',
        lastTransactionDate: '2015-04-13',
      },
      {
        footyWebNumber: '01635982',
        initials: 'RM',
        lastName: 'Masterson',
        firstName: 'Riley',
        gender: 'Male',
        lastTransactionDate: '2017-03-31',
      },
      {
        footyWebNumber: '02282130',
        initials: 'EM',
        lastName: 'Matheson',
        firstName: 'Emjay',
        gender: 'Male',
        lastTransactionDate: '2018-02-20',
      },
      {
        footyWebNumber: '02503907',
        initials: 'CO',
        lastName: "O'Brien",
        firstName: 'Charlie',
        gender: 'Male',
        lastTransactionDate: '2017-03-23',
      },
      {
        footyWebNumber: '02250406',
        initials: 'RP',
        lastName: 'Peers',
        firstName: 'Riley',
        gender: 'Male',
        lastTransactionDate: '2017-05-05',
      },
      {
        footyWebNumber: '02923006',
        initials: 'MP',
        lastName: 'Perez',
        firstName: 'Mason',
        gender: 'Male',
        lastTransactionDate: '2016-04-21',
      },
      {
        footyWebNumber: '02851182',
        initials: 'AP',
        lastName: 'Potter',
        firstName: 'Alex',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '01040203',
        initials: 'ZQ',
        lastName: 'Quaresima',
        firstName: 'Zac',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '02954335',
        initials: 'CR',
        lastName: 'Raine',
        firstName: 'Corey',
        gender: 'Male',
        lastTransactionDate: '2017-03-27',
      },
      {
        footyWebNumber: '02498546',
        initials: 'TT',
        lastName: 'Thompson',
        firstName: 'Tristan',
        gender: 'Male',
        lastTransactionDate: '2016-04-08',
      },
      {
        footyWebNumber: '02012813',
        initials: 'BT',
        lastName: 'Tomlinson',
        firstName: 'Bodhi',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '02062851',
        initials: 'KW',
        lastName: 'Williams',
        firstName: 'Kai',
        gender: 'Male',
        lastTransactionDate: '2017-12-06',
      },
    ],
  },
  U16G: {
    name: 'Under 16 Girls',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '03520214',
        initials: 'MC',
        lastName: 'Christensen',
        firstName: 'Mia',
        gender: 'Female',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03321278',
        initials: 'CJ',
        lastName: 'Johnson',
        firstName: 'Claire',
        gender: 'Female',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03237698',
        initials: 'RK',
        lastName: 'Khan',
        firstName: 'Rana',
        gender: 'Female',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03205317',
        initials: 'DS',
        lastName: 'Steele',
        firstName: 'Dakota',
        gender: 'Female',
        paidThisSeason: true,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03534656',
        initials: 'TA',
        lastName: 'Atcheson',
        firstName: 'Tilli',
        gender: 'Female',
        lastTransactionDate: '2020-06-20',
      },
      {
        footyWebNumber: '03548512',
        initials: 'MB',
        lastName: 'Blake',
        firstName: 'Mikybie',
        gender: 'Female',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '02733467',
        initials: 'MC',
        lastName: 'Cameron',
        firstName: 'Madelyn',
        gender: 'Female',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03007678',
        initials: 'ID',
        lastName: 'Darmawan',
        firstName: 'Indah',
        gender: 'Female',
        lastTransactionDate: '2019-11-14',
      },
      {
        footyWebNumber: '01601102',
        initials: 'RH',
        lastName: 'Heenan',
        firstName: 'Renee',
        gender: 'Female',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '03399767',
        initials: 'KH',
        lastName: 'Hodgkinson',
        firstName: 'Kayley',
        gender: 'Female',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '02921597',
        initials: 'CH',
        lastName: 'Hughson',
        firstName: 'Cassie',
        gender: 'Female',
        lastTransactionDate: '2019-12-02',
      },
      {
        footyWebNumber: '03041607',
        initials: 'ZI',
        lastName: 'Irshad',
        firstName: 'Zara',
        gender: 'Female',
        lastTransactionDate: '2019-04-06',
      },
      {
        footyWebNumber: '03399776',
        initials: 'PK',
        lastName: 'Khan',
        firstName: 'Pashtana',
        gender: 'Female',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '02915374',
        initials: 'JL',
        lastName: 'Leb',
        firstName: 'Jessica',
        gender: 'Female',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03305352',
        initials: 'AL',
        lastName: 'Lech',
        firstName: 'Amielle',
        gender: 'Female',
        lastTransactionDate: '2020-03-08',
      },
      {
        footyWebNumber: '03233700',
        initials: 'TM',
        lastName: 'Malone',
        firstName: 'Taylah',
        gender: 'Female',
        lastTransactionDate: '2020-02-18',
      },
      {
        footyWebNumber: '03323944',
        initials: 'EM',
        lastName: 'Maniscalchi',
        firstName: 'Emily',
        gender: 'Female',
        lastTransactionDate: '2020-03-09',
      },
      {
        footyWebNumber: '02469761',
        initials: 'GM',
        lastName: 'Marsden',
        firstName: 'Georgie',
        gender: 'Female',
        lastTransactionDate: '2020-02-01',
      },
      {
        footyWebNumber: '02505196',
        initials: 'MR',
        lastName: 'Robertson',
        firstName: 'Matilda',
        gender: 'Female',
        lastTransactionDate: '2019-05-06',
      },
      {
        footyWebNumber: '03917772',
        initials: 'SS',
        lastName: 'Self',
        firstName: 'Skye',
        gender: 'Female',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03322683',
        initials: 'NT',
        lastName: 'Thompson',
        firstName: 'Nikita',
        gender: 'Female',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '03150878',
        initials: 'GV',
        lastName: 'Vodopier',
        firstName: 'Gemma',
        gender: 'Female',
        lastTransactionDate: '2020-06-22',
      },
      {
        footyWebNumber: '02986477',
        initials: 'JW',
        lastName: 'Walters',
        firstName: 'Jade',
        gender: 'Female',
        lastTransactionDate: '2020-02-15',
      },
      {
        footyWebNumber: '03605606',
        initials: 'TW',
        lastName: 'Wilson',
        firstName: 'Tara',
        gender: 'Female',
        lastTransactionDate: '2020-06-27',
      },
      {
        footyWebNumber: '02678558',
        initials: 'RW',
        lastName: 'Wootton',
        firstName: 'Rhani',
        gender: 'Female',
        lastTransactionDate: '2020-02-17',
      },
      {
        footyWebNumber: '03226863',
        initials: 'CZR',
        lastName: 'Zouch-Ristic',
        firstName: 'Chloe',
        gender: 'Female',
        lastTransactionDate: '2020-01-20',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '03070934',
        initials: 'EB',
        lastName: 'Bamford',
        firstName: 'Evelyn',
        gender: 'Female',
        club: 'Ferntree Gully',
        lastTransferDate: '2020-06-27',
      },
      {
        footyWebNumber: '02011566',
        initials: 'TB',
        lastName: 'Burns',
        firstName: 'Torey',
        gender: 'Female',
        club: 'Vermont',
        lastTransferDate: '2020-11-17',
      },
      {
        footyWebNumber: '01644349',
        initials: 'MH',
        lastName: 'Hinton',
        firstName: 'Monique',
        gender: 'Female',
        club: 'Upper Ferntree Gully',
        lastTransferDate: '2018-03-01',
      },
      {
        footyWebNumber: '02915226',
        initials: 'MP',
        lastName: 'Plumridge',
        firstName: 'Mia',
        gender: 'Female',
        club: 'East Ringwood',
        lastTransferDate: '2019-11-20',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '02912249',
        initials: 'LB',
        lastName: 'Beatt',
        firstName: 'Latisha',
        gender: 'Female',
        lastTransactionDate: '2018-02-07',
      },
      {
        footyWebNumber: '02915191',
        initials: 'TB(',
        lastName: 'Brown (Reddecliffe)',
        firstName: 'Tayla',
        gender: 'Female',
        lastTransactionDate: '2016-04-15',
      },
      {
        footyWebNumber: '03319479',
        initials: 'CF',
        lastName: 'Francis',
        firstName: 'Charlotte',
        gender: 'Female',
        lastTransactionDate: '2018-04-28',
      },
      {
        footyWebNumber: '03003389',
        initials: 'JM',
        lastName: 'McAuliffe',
        firstName: 'Jasmine',
        gender: 'Female',
        lastTransactionDate: '2018-02-22',
      },
      {
        footyWebNumber: '01843979',
        initials: 'TM',
        lastName: 'McGuire',
        firstName: 'Tia',
        gender: 'Female',
        lastTransactionDate: '2015-05-29',
      },
      {
        footyWebNumber: '03067710',
        initials: 'JM',
        lastName: 'McLachlan',
        firstName: 'Jayde',
        gender: 'Female',
        lastTransactionDate: '2017-03-20',
      },
      {
        footyWebNumber: '01931091',
        initials: 'PS',
        lastName: 'Scott',
        firstName: 'Paige',
        gender: 'Female',
        lastTransactionDate: '2017-02-04',
      },
      {
        footyWebNumber: '03359394',
        initials: 'DS',
        lastName: 'Suarez',
        firstName: 'Darci',
        gender: 'Female',
        lastTransactionDate: '2018-07-19',
      },
      {
        footyWebNumber: '02915130',
        initials: 'NT',
        lastName: 'Taherzadeh',
        firstName: 'Nahal',
        gender: 'Female',
        lastTransactionDate: '2017-04-01',
      },
    ],
  },
  U14B: {
    name: 'Under 14 Boys',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '02474446',
        initials: 'NA',
        lastName: 'Anderson',
        firstName: 'Noah',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '01838065',
        initials: 'DD',
        lastName: 'Derham',
        firstName: 'David',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03081833',
        initials: 'CH',
        lastName: 'Hannan',
        firstName: 'Chad',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02311432',
        initials: 'JR',
        lastName: 'Rimmer',
        firstName: 'James',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02640219',
        initials: 'RR',
        lastName: 'Roberts',
        firstName: 'Rohan',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03329538',
        initials: 'JB',
        lastName: 'Buchstaller',
        firstName: 'Joshua',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02280414',
        initials: 'RC',
        lastName: 'Collins',
        firstName: 'Riley',
        gender: 'Male',
        lastTransactionDate: '2019-01-14',
      },
      {
        footyWebNumber: '02058704',
        initials: 'ZD',
        lastName: 'Darmawan',
        firstName: 'Zyon',
        gender: 'Male',
        lastTransactionDate: '2019-11-14',
      },
      {
        footyWebNumber: '03355238',
        initials: 'AE',
        lastName: 'Edwards',
        firstName: 'Aidan',
        gender: 'Male',
        lastTransactionDate: '2018-11-12',
      },
      {
        footyWebNumber: '02073542',
        initials: 'MG',
        lastName: 'Gordon',
        firstName: 'Malakai',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02898108',
        initials: 'EH',
        lastName: 'Hapuarachchi',
        firstName: 'Ezra',
        gender: 'Male',
        lastTransactionDate: '2020-02-26',
      },
      {
        footyWebNumber: '02278176',
        initials: 'JH',
        lastName: 'Harris',
        firstName: 'Joel',
        gender: 'Male',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '04028466',
        initials: 'JH',
        lastName: 'Hasslinger',
        firstName: 'Joshua',
        gender: 'Male',
        lastTransactionDate: '2020-06-20',
      },
      {
        footyWebNumber: '03034522',
        initials: 'OL',
        lastName: 'Ludtke',
        firstName: 'Oscar',
        gender: 'Male',
        lastTransactionDate: '2020-02-29',
      },
      {
        footyWebNumber: '03069571',
        initials: 'TM',
        lastName: 'Mathews',
        firstName: 'Toby',
        gender: 'Male',
        lastTransactionDate: '2019-11-11',
      },
      {
        footyWebNumber: '02233038',
        initials: 'JP',
        lastName: 'Pepperell',
        firstName: 'Jackson',
        gender: 'Male',
        lastTransactionDate: '2018-12-23',
      },
      {
        footyWebNumber: '02341330',
        initials: 'JP',
        lastName: 'Peters',
        firstName: 'Jackson',
        gender: 'Male',
        lastTransactionDate: '2020-06-25',
      },
      {
        footyWebNumber: '02016728',
        initials: 'OP',
        lastName: 'Prior',
        firstName: 'Owen',
        gender: 'Male',
        lastTransactionDate: '2020-06-18',
      },
      {
        footyWebNumber: '02256004',
        initials: 'AS',
        lastName: 'Samos',
        firstName: 'Alex',
        gender: 'Male',
        lastTransactionDate: '2020-06-01',
      },
      {
        footyWebNumber: '03787511',
        initials: 'AS',
        lastName: 'Stoddart',
        firstName: 'Anthony',
        gender: 'Male',
        lastTransactionDate: '2019-11-03',
      },
      {
        footyWebNumber: '02043435',
        initials: 'XW',
        lastName: 'Wood',
        firstName: 'Xavier',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '02762847',
        initials: 'CY',
        lastName: 'Young',
        firstName: 'Campbell',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '02282039',
        initials: 'CK',
        lastName: 'kleverkamp',
        firstName: 'cody',
        gender: 'Male',
        lastTransactionDate: '2019-04-01',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '02632063',
        initials: 'HB',
        lastName: 'Boehl',
        firstName: 'Hayden',
        gender: 'Male',
        club: 'Wantirna South',
        lastTransferDate: '2018-11-25',
      },
      {
        footyWebNumber: '02254838',
        initials: 'CC',
        lastName: 'Curtain',
        firstName: 'Charlie',
        gender: 'Male',
        club: 'Ferntree Gully',
        lastTransferDate: '2018-04-04',
      },
      {
        footyWebNumber: '02001335',
        initials: 'JG',
        lastName: 'Gilchrist',
        firstName: 'Jamie',
        gender: 'Male',
        club: 'East Ringwood',
        lastTransferDate: '2020-06-16',
      },
      {
        footyWebNumber: '02274028',
        initials: 'BM',
        lastName: 'Mainenti',
        firstName: 'Blake',
        gender: 'Male',
        club: 'Knox',
        lastTransferDate: '2018-11-24',
      },
      {
        footyWebNumber: '02051529',
        initials: 'SN',
        lastName: 'Newey',
        firstName: 'Sam',
        gender: 'Male',
        club: 'The Basin',
        lastTransferDate: '2017-11-16',
      },
      {
        footyWebNumber: '03103495',
        initials: 'AT',
        lastName: 'Tong',
        firstName: 'Alier',
        gender: 'Male',
        club: 'Montrose',
        lastTransferDate: '2017-07-01',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '02683610',
        initials: 'NC',
        lastName: 'Caird',
        firstName: 'Nicholas',
        gender: 'Male',
        lastTransactionDate: '2017-03-30',
      },
      {
        footyWebNumber: '02221841',
        initials: 'OJ',
        lastName: 'Jones',
        firstName: 'Oliver',
        gender: 'Male',
        lastTransactionDate: '2018-04-21',
      },
      {
        footyWebNumber: '03081384',
        initials: 'WO',
        lastName: 'Obrien',
        firstName: 'William',
        gender: 'Male',
        lastTransactionDate: '2017-03-29',
      },
      {
        footyWebNumber: '02286476',
        initials: 'JP',
        lastName: 'Peppler',
        firstName: 'Jack',
        gender: 'Male',
        lastTransactionDate: '2017-03-30',
      },
      {
        footyWebNumber: '01825672',
        initials: 'JR',
        lastName: 'Robins',
        firstName: 'Jackson',
        gender: 'Male',
        lastTransactionDate: '2017-03-31',
      },
      {
        footyWebNumber: '03085445',
        initials: 'BS',
        lastName: 'Scott',
        firstName: 'Brodie',
        gender: 'Male',
        lastTransactionDate: '2018-04-21',
      },
      {
        footyWebNumber: '02051875',
        initials: 'AS',
        lastName: 'Stafford',
        firstName: 'Aiden',
        gender: 'Male',
        lastTransactionDate: '2016-04-01',
      },
      {
        footyWebNumber: '03255861',
        initials: 'PTN',
        lastName: 'Tuigamala-Nukunuku',
        firstName: 'Pakura Johnson',
        gender: 'Male',
        lastTransactionDate: '2018-03-15',
      },
      {
        footyWebNumber: '03108917',
        initials: 'PTF',
        lastName: 'Tuigamala-faasalafa',
        firstName: 'Pakura Johnson',
        gender: 'Male',
        lastTransactionDate: '2017-04-19',
      },
      {
        footyWebNumber: '03247163',
        initials: 'NUM',
        lastName: 'Ul-Malik',
        firstName: 'Naim',
        gender: 'Male',
        lastTransactionDate: '2018-03-07',
      },
      {
        footyWebNumber: '02699556',
        initials: 'TU',
        lastName: 'Urban',
        firstName: 'Tyler',
        gender: 'Male',
        lastTransactionDate: '2018-04-04',
      },
      {
        footyWebNumber: '03749910',
        initials: 'BW',
        lastName: 'White',
        firstName: 'Blake',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '02256193',
        initials: 'TR',
        lastName: 'rogers',
        firstName: 'travis',
        gender: 'Male',
        lastTransactionDate: '2016-03-29',
      },
    ],
  },
  U14G: {
    name: 'Under 14 Girls',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '02464774',
        initials: 'MH',
        lastName: 'Hindson',
        firstName: 'Matilda',
        gender: 'Female',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03399779',
        initials: 'AK',
        lastName: 'King',
        firstName: 'Acacia-Lee',
        gender: 'Female',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03217083',
        initials: 'SS',
        lastName: 'Soderman',
        firstName: 'Summer-lee',
        gender: 'Female',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03070939',
        initials: 'JB',
        lastName: 'Bamford',
        firstName: 'Josephine',
        gender: 'Female',
        lastTransactionDate: '2020-01-06',
      },
      {
        footyWebNumber: '03325019',
        initials: 'HC',
        lastName: 'Carter',
        firstName: 'Hailey',
        gender: 'Female',
        lastTransactionDate: '2020-07-02',
      },
      {
        footyWebNumber: '03649305',
        initials: 'EC',
        lastName: 'Cossens',
        firstName: 'Elena',
        gender: 'Female',
        lastTransactionDate: '2019-04-17',
      },
      {
        footyWebNumber: '03567530',
        initials: 'GH',
        lastName: 'Hughson',
        firstName: 'Gemma',
        gender: 'Female',
        lastTransactionDate: '2019-12-02',
      },
      {
        footyWebNumber: '03310052',
        initials: 'AJ',
        lastName: 'Johnson',
        firstName: 'Amy',
        gender: 'Female',
        lastTransactionDate: '2020-02-17',
      },
      {
        footyWebNumber: '03560928',
        initials: 'EM',
        lastName: 'Macfarlane',
        firstName: 'Emily',
        gender: 'Female',
        lastTransactionDate: '2020-06-21',
      },
      {
        footyWebNumber: '03720647',
        initials: 'KN',
        lastName: 'Nackovski',
        firstName: 'Kristina',
        gender: 'Female',
        lastTransactionDate: '2019-05-10',
      },
      {
        footyWebNumber: '03399833',
        initials: 'KN',
        lastName: 'Niksic',
        firstName: 'Kayla',
        gender: 'Female',
        lastTransactionDate: '2018-11-11',
      },
      {
        footyWebNumber: '02256741',
        initials: 'SR',
        lastName: 'Rennison',
        firstName: 'Sydney',
        gender: 'Female',
        lastTransactionDate: '2020-06-18',
      },
      {
        footyWebNumber: '03056282',
        initials: 'KR',
        lastName: 'Rogers',
        firstName: 'Kendall',
        gender: 'Female',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '03512092',
        initials: 'TS',
        lastName: 'Stocker',
        firstName: 'Tori',
        gender: 'Female',
        lastTransactionDate: '2020-07-03',
      },
      {
        footyWebNumber: '02211926',
        initials: 'KT',
        lastName: 'Torney',
        firstName: 'Kiara',
        gender: 'Female',
        lastTransactionDate: '2019-03-29',
      },
    ],
    membersTransferred: [],
    membersOther: [
      {
        footyWebNumber: '03251681',
        initials: 'RH',
        lastName: 'Harrison',
        firstName: 'Rhianna',
        gender: 'Female',
        lastTransactionDate: '2018-03-12',
      },
      {
        footyWebNumber: '02456464',
        initials: 'ML',
        lastName: 'Lewis',
        firstName: 'Mikayla',
        gender: 'Female',
        lastTransactionDate: '2017-03-28',
      },
      {
        footyWebNumber: '03086852',
        initials: 'RP',
        lastName: 'Paras',
        firstName: 'Rubee',
        gender: 'Female',
        lastTransactionDate: '2017-03-31',
      },
      {
        footyWebNumber: '03087991',
        initials: 'CR',
        lastName: 'Ramadge',
        firstName: 'Chelsea',
        gender: 'Female',
        lastTransactionDate: '2017-04-01',
      },
      {
        footyWebNumber: '02639396',
        initials: 'AM',
        lastName: 'matheson',
        firstName: 'ava',
        gender: 'Female',
        lastTransactionDate: '2018-02-20',
      },
    ],
  },
  U12G: {
    name: 'Under 12 Girls',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '04033359',
        initials: 'CB',
        lastName: 'Brady',
        firstName: 'Charlotte',
        gender: 'Female',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03100805',
        initials: 'EF',
        lastName: 'Ferguson',
        firstName: 'Emily',
        gender: 'Female',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '04034442',
        initials: 'RM',
        lastName: 'McGuire',
        firstName: 'Remi',
        gender: 'Female',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03255492',
        initials: 'CR',
        lastName: 'Robertson',
        firstName: 'Charlie',
        gender: 'Female',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03319490',
        initials: 'SS',
        lastName: 'Soderman',
        firstName: 'Skye',
        gender: 'Female',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03584559',
        initials: 'SG',
        lastName: 'GauciFraser',
        firstName: 'Shaylee',
        gender: 'Female',
        lastTransactionDate: '2019-04-06',
      },
      {
        footyWebNumber: '03869795',
        initials: 'TL',
        lastName: 'Lovie',
        firstName: 'Taiha',
        gender: 'Female',
        lastTransactionDate: '2019-11-09',
      },
      {
        footyWebNumber: '03323972',
        initials: 'GM',
        lastName: 'Maniscalchi',
        firstName: 'Grace',
        gender: 'Female',
        lastTransactionDate: '2020-03-09',
      },
      {
        footyWebNumber: '03511285',
        initials: 'ZM',
        lastName: 'Morgans',
        firstName: 'Zoe',
        gender: 'Female',
        lastTransactionDate: '2019-02-17',
      },
      {
        footyWebNumber: '03869871',
        initials: 'CW',
        lastName: 'Willcock',
        firstName: 'Carly',
        gender: 'Female',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '03980514',
        initials: 'KW',
        lastName: 'Wood',
        firstName: 'Keely',
        gender: 'Female',
        lastTransactionDate: '2020-03-11',
      },
    ],
    membersTransferred: [],
    membersOther: [],
  },
  U12B: {
    name: 'Under 12 Boys',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '02451070',
        initials: 'XB',
        lastName: 'Bickers',
        firstName: 'Xavier',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02470918',
        initials: 'BS',
        lastName: 'Sales',
        firstName: 'Blake',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02457999',
        initials: 'BT',
        lastName: 'Talia',
        firstName: 'Brodie',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '04074731',
        initials: 'JT',
        lastName: 'Templeton',
        firstName: 'Jett',
        gender: 'Male',
        paidThisSeason: true,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03505718',
        initials: 'VB',
        lastName: 'Beattie',
        firstName: 'Vaughn',
        gender: 'Male',
        lastTransactionDate: '2019-02-17',
      },
      {
        footyWebNumber: '03018872',
        initials: 'RB',
        lastName: 'Beveridge',
        firstName: 'Ryder',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02832014',
        initials: 'JG',
        lastName: 'Groenewegen',
        firstName: 'Jasper',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02625774',
        initials: 'JH',
        lastName: 'Hannan',
        firstName: 'Jett',
        gender: 'Male',
        lastTransactionDate: '2019-11-02',
      },
      {
        footyWebNumber: '02753434',
        initials: 'TH',
        lastName: 'Hurrell',
        firstName: 'Taj',
        gender: 'Male',
        lastTransactionDate: '2020-07-01',
      },
      {
        footyWebNumber: '03083339',
        initials: 'ZM',
        lastName: 'Maloney',
        firstName: 'Zakiya',
        gender: 'Male',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '02469746',
        initials: 'JM',
        lastName: 'Marsden',
        firstName: 'Jed',
        gender: 'Male',
        lastTransactionDate: '2020-02-01',
      },
      {
        footyWebNumber: '02568230',
        initials: 'LP',
        lastName: 'Page',
        firstName: 'Liam',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02755238',
        initials: 'ZP',
        lastName: 'Parker',
        firstName: 'Zac',
        gender: 'Male',
        lastTransactionDate: '2020-03-03',
      },
      {
        footyWebNumber: '03082639',
        initials: 'TR',
        lastName: 'Rippon',
        firstName: 'Tyler',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02874729',
        initials: 'JR',
        lastName: 'Roberts',
        firstName: 'Joshua',
        gender: 'Male',
        lastTransactionDate: '2020-03-05',
      },
      {
        footyWebNumber: '03510781',
        initials: 'RR',
        lastName: 'Russell',
        firstName: 'Ryan',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03014226',
        initials: 'MS',
        lastName: 'Smith',
        firstName: 'Mateo',
        gender: 'Male',
        lastTransactionDate: '2020-02-10',
      },
      {
        footyWebNumber: '02568249',
        initials: 'TW',
        lastName: 'Willoughby',
        firstName: 'Tyler',
        gender: 'Male',
        lastTransactionDate: '2020-06-18',
      },
      {
        footyWebNumber: '02436867',
        initials: 'AW',
        lastName: 'Wootton',
        firstName: 'Axel',
        gender: 'Male',
        lastTransactionDate: '2020-02-20',
      },
      {
        footyWebNumber: '02743856',
        initials: 'MK',
        lastName: 'knight',
        firstName: 'mitchell',
        gender: 'Male',
        lastTransactionDate: '2020-03-02',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '02480488',
        initials: 'MH',
        lastName: 'Hiscock',
        firstName: 'Maximus',
        gender: 'Male',
        club: 'The Basin',
        lastTransferDate: '2017-03-27',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '03247167',
        initials: 'SUM',
        lastName: 'Ul-Malik',
        firstName: 'Sahid',
        gender: 'Male',
        lastTransactionDate: '2018-03-07',
      },
    ],
  },
  U11M: {
    name: 'Under 11 Mixed',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '02845428',
        initials: 'TB',
        lastName: 'Barbour',
        firstName: 'Tyler',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03541757',
        initials: 'LB',
        lastName: 'Bone',
        firstName: 'Lily',
        gender: 'Female',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03201604',
        initials: 'LM',
        lastName: 'McPherson',
        firstName: 'Levi',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '02892610',
        initials: 'TW',
        lastName: 'Walker',
        firstName: 'Thomas',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '02859250',
        initials: 'TW',
        lastName: 'Walker',
        firstName: 'Tyler',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '02666938',
        initials: 'OS',
        lastName: 'spencer',
        firstName: 'owen',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '02869775',
        initials: 'HB',
        lastName: 'Bithell',
        firstName: 'Hamish',
        gender: 'Male',
        lastTransactionDate: '2020-03-10',
      },
      {
        footyWebNumber: '03062353',
        initials: 'MB',
        lastName: 'Bullman',
        firstName: 'Miller',
        gender: 'Male',
        lastTransactionDate: '2020-02-13',
      },
      {
        footyWebNumber: '02870196',
        initials: 'JC',
        lastName: 'Cook',
        firstName: 'James',
        gender: 'Male',
        lastTransactionDate: '2020-06-18',
      },
      {
        footyWebNumber: '03342147',
        initials: 'SD',
        lastName: 'Davies',
        firstName: 'Sam',
        gender: 'Male',
        lastTransactionDate: '2020-03-15',
      },
      {
        footyWebNumber: '02896196',
        initials: 'AE',
        lastName: 'Eagles',
        firstName: 'Ashton',
        gender: 'Male',
        lastTransactionDate: '2020-02-06',
      },
      {
        footyWebNumber: '02869796',
        initials: 'JG',
        lastName: 'Gunn',
        firstName: 'Joel',
        gender: 'Male',
        lastTransactionDate: '2020-02-12',
      },
      {
        footyWebNumber: '03546905',
        initials: 'LK',
        lastName: 'Kershaw',
        firstName: 'Leila',
        gender: 'Female',
        lastTransactionDate: '2020-02-13',
      },
      {
        footyWebNumber: '02849448',
        initials: 'MP',
        lastName: 'Parlby',
        firstName: 'Marley',
        gender: 'Male',
        lastTransactionDate: '2020-03-11',
      },
      {
        footyWebNumber: '02706999',
        initials: 'JP',
        lastName: 'Pearson',
        firstName: 'Jack',
        gender: 'Male',
        lastTransactionDate: '2020-02-05',
      },
      {
        footyWebNumber: '02694971',
        initials: 'MP',
        lastName: 'Peters',
        firstName: 'Max',
        gender: 'Male',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '02665581',
        initials: 'RP',
        lastName: 'Pickett',
        firstName: 'Riley',
        gender: 'Male',
        lastTransactionDate: '2019-02-24',
      },
      {
        footyWebNumber: '02871178',
        initials: 'LR',
        lastName: 'Raymond',
        firstName: 'Logan',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '03033557',
        initials: 'IT',
        lastName: 'Tauiliili',
        firstName: 'Izaac',
        gender: 'Male',
        lastTransactionDate: '2020-06-20',
      },
      {
        footyWebNumber: '03340038',
        initials: 'JT',
        lastName: 'Toohey',
        firstName: 'Joshua',
        gender: 'Male',
        lastTransactionDate: '2020-02-15',
      },
      {
        footyWebNumber: '02672155',
        initials: 'BT',
        lastName: 'Tournier',
        firstName: 'Billy',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03867608',
        initials: 'DT',
        lastName: 'Turin',
        firstName: 'Darrell',
        gender: 'Male',
        lastTransactionDate: '2019-11-02',
      },
      {
        footyWebNumber: '03869872',
        initials: 'JW',
        lastName: 'Willcock',
        firstName: 'Jessica',
        gender: 'Female',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '02762350',
        initials: 'MW',
        lastName: 'Woolard',
        firstName: 'Martin',
        gender: 'Male',
        lastTransactionDate: '2020-02-15',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '02694004',
        initials: 'NH',
        lastName: 'Hoggett',
        firstName: 'Noah',
        gender: 'Male',
        club: 'Upper Ferntree Gully',
        lastTransferDate: '2020-06-13',
      },
      {
        footyWebNumber: '02693547',
        initials: 'TO',
        lastName: 'Ofield',
        firstName: 'Tyler',
        gender: 'Male',
        club: 'Rowville Hawks',
        lastTransferDate: '2018-02-20',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '02928071',
        initials: 'CM',
        lastName: 'Miller',
        firstName: 'Cooper',
        gender: 'Male',
        lastTransactionDate: '2018-04-23',
      },
      {
        footyWebNumber: '03318271',
        initials: 'BM',
        lastName: 'Munro',
        firstName: 'Boyd',
        gender: 'Male',
        lastTransactionDate: '2018-05-02',
      },
    ],
  },
  U10M: {
    name: 'Under 10 Mixed',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '03558237',
        initials: 'JAH',
        lastName: 'Ash-Hall',
        firstName: 'Jayden',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '02853496',
        initials: 'DM',
        lastName: 'Moore',
        firstName: 'Dustyn',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03258258',
        initials: 'OA',
        lastName: 'Amey',
        firstName: 'Oliver',
        gender: 'Male',
        lastTransactionDate: '2020-07-01',
      },
      {
        footyWebNumber: '03223491',
        initials: 'JB',
        lastName: 'Bartling',
        firstName: 'Jaxon',
        gender: 'Male',
        lastTransactionDate: '2020-02-15',
      },
      {
        footyWebNumber: '03018873',
        initials: 'PB',
        lastName: 'Beveridge',
        firstName: 'Phoenix',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '03062355',
        initials: 'KB',
        lastName: 'Bullman',
        firstName: 'Kane',
        gender: 'Male',
        lastTransactionDate: '2020-02-13',
      },
      {
        footyWebNumber: '03062354',
        initials: 'TB',
        lastName: 'Bullman',
        firstName: 'Tyler',
        gender: 'Male',
        lastTransactionDate: '2020-02-13',
      },
      {
        footyWebNumber: '03068383',
        initials: 'MH',
        lastName: 'Hughson',
        firstName: 'Max',
        gender: 'Male',
        lastTransactionDate: '2019-12-02',
      },
      {
        footyWebNumber: '02884609',
        initials: 'JH',
        lastName: 'Hurrell',
        firstName: 'Jai',
        gender: 'Male',
        lastTransactionDate: '2020-07-01',
      },
      {
        footyWebNumber: '03100492',
        initials: 'CI',
        lastName: 'Irvin',
        firstName: 'Cooper',
        gender: 'Male',
        lastTransactionDate: '2020-02-22',
      },
      {
        footyWebNumber: '03350677',
        initials: 'JM',
        lastName: 'Mead',
        firstName: 'Jackson',
        gender: 'Male',
        lastTransactionDate: '2019-11-09',
      },
      {
        footyWebNumber: '03064832',
        initials: 'MM',
        lastName: 'Murphy',
        firstName: 'Maison',
        gender: 'Male',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '03560394',
        initials: 'DN',
        lastName: 'Nackovski',
        firstName: 'David',
        gender: 'Male',
        lastTransactionDate: '2020-02-27',
      },
      {
        footyWebNumber: '03249514',
        initials: 'NN',
        lastName: 'Nicolaou',
        firstName: 'Noah',
        gender: 'Male',
        lastTransactionDate: '2020-01-21',
      },
      {
        footyWebNumber: '03400860',
        initials: 'LT',
        lastName: 'Torney',
        firstName: 'Lachlan',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03588457',
        initials: 'SW',
        lastName: 'Wootten',
        firstName: 'Seth Max',
        gender: 'Male',
        lastTransactionDate: '2020-06-19',
      },
    ],
    membersTransferred: [
      {
        footyWebNumber: '03058040',
        initials: 'AK',
        lastName: 'Kolb',
        firstName: 'Andrew',
        gender: 'Male',
        club: 'North Ringwood',
        lastTransferDate: '2020-11-17',
      },
    ],
    membersOther: [
      {
        footyWebNumber: '03283702',
        initials: 'MC',
        lastName: 'Cullen',
        firstName: 'Mason',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '03049482',
        initials: 'RP',
        lastName: 'Perry',
        firstName: 'Ryan',
        gender: 'Male',
        lastTransactionDate: '2017-11-12',
      },
      {
        footyWebNumber: '03885213',
        initials: 'LW',
        lastName: 'White',
        firstName: 'Landon',
        gender: 'Male',
        lastTransactionDate: null,
      },
      {
        footyWebNumber: '03287395',
        initials: 'SW',
        lastName: 'Wootten',
        firstName: 'Seth',
        gender: 'Male',
        lastTransactionDate: null,
      },
    ],
  },
  U09M: {
    name: 'Under 9 Mixed',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '03064071',
        initials: 'CB',
        lastName: 'Barbour',
        firstName: 'Cooper',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03241282',
        initials: 'WB',
        lastName: 'Bone',
        firstName: 'William',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03055429',
        initials: 'KC',
        lastName: 'Collins',
        firstName: 'Kai',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03247587',
        initials: 'LG',
        lastName: 'Guymer',
        firstName: 'Lawson',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03091295',
        initials: 'ZH',
        lastName: 'Hindson',
        firstName: 'Zach',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03065674',
        initials: 'SJ',
        lastName: 'Jolly',
        firstName: 'Sid',
        gender: 'Male',
        paidThisSeason: true,
      },
      {
        footyWebNumber: '03136096',
        initials: 'LR',
        lastName: 'Robertson',
        firstName: 'Luca',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03343780',
        initials: 'TA',
        lastName: 'Ashton',
        firstName: 'Tigerlily',
        gender: 'Female',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '03310424',
        initials: 'AB',
        lastName: 'Baseden',
        firstName: 'Adam',
        gender: 'Male',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '03561703',
        initials: 'MC',
        lastName: 'Cincotta',
        firstName: 'Markus',
        gender: 'Male',
        lastTransactionDate: '2020-02-15',
      },
      {
        footyWebNumber: '03058232',
        initials: 'JH',
        lastName: 'Hartley',
        firstName: 'Jackson',
        gender: 'Male',
        lastTransactionDate: '2020-02-17',
      },
      {
        footyWebNumber: '03055886',
        initials: 'DK',
        lastName: 'Kinstler',
        firstName: 'Dustin',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
      {
        footyWebNumber: '03087332',
        initials: 'LR',
        lastName: 'Raymond',
        firstName: 'Levi',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
      {
        footyWebNumber: '03917071',
        initials: 'LW',
        lastName: 'White',
        firstName: 'Levi',
        gender: 'Male',
        lastTransactionDate: '2020-02-16',
      },
    ],
    membersTransferred: [],
    membersOther: [],
  },
  U08M: {
    name: 'Under 8 Mixed',
    membersRegisteredThisSeason: [
      {
        footyWebNumber: '03278431',
        initials: 'LF',
        lastName: 'Fitzpatrick',
        firstName: 'Levi',
        gender: 'Male',
        paidThisSeason: false,
      },
      {
        footyWebNumber: '03491580',
        initials: 'CJ',
        lastName: 'Jones',
        firstName: 'Caleb',
        gender: 'Male',
        paidThisSeason: false,
      },
    ],
    membersRegisteredRecently: [
      {
        footyWebNumber: '03241096',
        initials: 'HK',
        lastName: 'Knight',
        firstName: 'Heath',
        gender: 'Male',
        lastTransactionDate: '2020-06-19',
      },
      {
        footyWebNumber: '03268326',
        initials: 'ER',
        lastName: 'Rippon',
        firstName: 'Ethan',
        gender: 'Male',
        lastTransactionDate: '2019-11-10',
      },
    ],
    membersTransferred: [],
    membersOther: [],
  },
};
