export default [
  {
    code: 'U18G',
    ageGroupCode: 'U18',
    name: 'Under 18 Girls',
    teamGender: 'Female',
    headCoach: null,
    assistantCoach: null,
    trainer: null,
    teamManager: null,
    registeredCount: 1,
    paidCount: 0,
  },
  {
    code: 'U17B-GREEN',
    ageGroupCode: 'U16',
    name: 'Under 17 Boys (Green)',
    teamGender: 'Male',
    headCoach: {
      firstName: 'Lachie',
      lastName: 'McGuire',
    },
    assistantCoach: {
      firstName: 'Nic',
      lastName: 'Maxwell',
    },
    trainer: {
      firstName: 'Rob',
      lastName: 'Scripps',
    },
    teamManager: {
      firstName: 'Kelly',
      lastName: 'McGuire',
    },
    registeredCount: 2,
    paidCount: 1,
  },
  {
    code: 'U17B-GOLD',
    ageGroupCode: 'U17',
    name: 'Under 17 Boys (Gold)',
    teamGender: 'Male',
    headCoach: {
      firstName: 'Jarrod',
      lastName: 'Amey',
    },
    assistantCoach: {
      firstName: 'Danny',
      lastName: 'Phillips',
    },
    trainer: {
      firstName: 'Kim',
      lastName: 'Phillips',
    },
    teamManager: {
      firstName: 'Deanna',
      lastName: 'Derham',
    },
    registeredCount: 8,
    paidCount: 6,
  },
  {
    code: 'U16G',
    ageGroupCode: 'U16',
    name: 'Under 16 Girls',
    teamGender: 'Female',
    headCoach: {
      firstName: 'Michael',
      lastName: 'Hughson',
    },
    assistantCoach: null,
    trainer: null,
    teamManager: {
      firstName: 'Kylie',
      lastName: 'Cameron',
    },
    registeredCount: 4,
    paidCount: 4,
  },
  {
    code: 'U14G',
    ageGroupCode: 'U14',
    name: 'Under 14 Girls',
    teamGender: 'Female',
    headCoach: {
      firstName: 'Matt',
      lastName: 'Rennison',
    },
    assistantCoach: null,
    trainer: {
      firstName: 'Dragana',
      lastName: 'Hindson',
    },
    teamManager: null,
    registeredCount: 3,
    paidCount: 1,
  },
  {
    code: 'U14B',
    ageGroupCode: 'U14',
    name: 'Under 14 Boys',
    teamGender: 'Male',
    headCoach: {
      firstName: 'Andrew',
      lastName: 'Peters',
    },
    assistantCoach: {
      firstName: 'Steve',
      lastName: 'Roberts',
    },
    trainer: null,
    teamManager: {
      firstName: 'Deanna',
      lastName: 'Derham',
    },
    registeredCount: 5,
    paidCount: 3,
  },
  {
    code: 'U12G',
    ageGroupCode: 'U12',
    name: 'Under 12 Girls',
    teamGender: 'Female',
    headCoach: {
      firstName: 'Kevin',
      lastName: 'Maniscalchi',
    },
    assistantCoach: null,
    trainer: null,
    teamManager: null,
    registeredCount: 5,
    paidCount: 1,
  },
  {
    code: 'U12B',
    ageGroupCode: 'U12',
    name: 'Under 12 Boys',
    teamGender: 'Male',
    headCoach: {
      firstName: 'Andrew',
      lastName: 'Rippon',
    },
    assistantCoach: {
      firstName: 'Andrew',
      lastName: 'Parker',
    },
    trainer: null,
    teamManager: {
      firstName: 'Beccy',
      lastName: 'Dawber',
    },
    registeredCount: 4,
    paidCount: 4,
  },
  {
    code: 'U11M',
    ageGroupCode: 'U11',
    name: 'Under 11 Mixed',
    teamGender: 'Mixed',
    headCoach: {
      firstName: 'Alex',
      lastName: 'Gunn',
    },
    assistantCoach: null,
    trainer: null,
    teamManager: {
      firstName: 'Deb',
      lastName: 'Pearson',
    },
    registeredCount: 6,
    paidCount: 2,
  },
  {
    code: 'U10M',
    ageGroupCode: 'U10',
    name: 'Under 10 Mixed',
    teamGender: 'Mixed',
    headCoach: {
      firstName: 'Ben',
      lastName: 'Beveridge',
    },
    assistantCoach: {
      firstName: 'Erin',
      lastName: 'Chamberlain',
    },
    trainer: null,
    teamManager: null,
    registeredCount: 2,
    paidCount: 0,
  },
  {
    code: 'U09M',
    ageGroupCode: 'U9',
    name: 'Under 9 Mixed',
    teamGender: 'Mixed',
    headCoach: {
      firstName: 'Mark',
      lastName: 'Hindson',
    },
    assistantCoach: {
      firstName: 'Rob',
      lastName: 'Kinstler',
    },
    trainer: null,
    teamManager: null,
    registeredCount: 7,
    paidCount: 3,
  },
  {
    code: 'U08M',
    ageGroupCode: 'U8',
    name: 'Under 8 Mixed',
    teamGender: 'Mixed',
    headCoach: null,
    assistantCoach: null,
    trainer: null,
    teamManager: null,
    registeredCount: 2,
    paidCount: 0,
  },
];
