seasonYear: 2021
clubMap:
  - { from: Ashwood Junior Football Club, to: Ashwood }
  - { from: Bayswater Blues Primary School Football Club, to: Bayswater Blues PS }
  - { from: Berwick JFC, to: Berwick }
  - { from: Berwick North Junior Football Club, to: Berwick North }
  - { from: Doncaster JFC, to: Doncaster }
  - { from: Donvale Crusaders Primary School Football Club, to: Donvale Crusaders PS }
  - { from: Ferntree Gully Eagles, to: Ferntree Gully }
  - { from: Fitzroy Stars, to: Fitzroy }
  - { from: Mount Evelyn Junior Football Club, to: Mount Evelyn }
  - { from: Rowville Hawks Football Club, to: Rowville Hawks }
  - { from: Rowville Knights Community Football Club, to: Rowville Knights }
  - { from: Woori Yallock Junior Football Club, to: Woori Yallock }
noContact:
  - { footyWebNumber: sample }
playerTeamExceptions: 
  - { code: U12B, footyWebNumber: 02892610 }
