seasonYear: 2021
clubMap:
  - { from: Ashwood Junior Football Club, to: Ashwood }
  - { from: Bayswater Blues Primary School Football Club, to: Bayswater Blues PS }
  - { from: Berwick JFC, to: Berwick }
  - { from: Berwick North Junior Football Club, to: Berwick North }
  - { from: Doncaster JFC, to: Doncaster }
  - { from: Donvale Crusaders Primary School Football Club, to: Donvale Crusaders PS }
  - { from: Ferntree Gully Eagles, to: Ferntree Gully }
  - { from: Fitzroy Stars, to: Fitzroy }
  - { from: Mount Evelyn Junior Football Club, to: Mount Evelyn }
  - { from: Rowville Hawks Football Club, to: Rowville Hawks }
  - { from: Rowville Knights Community Football Club, to: Rowville Knights }
  - { from: Woori Yallock Junior Football Club, to: Woori Yallock }
noContact:
  - { footyWebNumber: '02505196' } # Matilda Robertson: Made it pretty clear she no longer wants to play (AR)
  - { footyWebNumber: '03399776' } # Pashtana Khan: Made it pretty clear she no longer wants to play (AR)  
  - { footyWebNumber: '03399767' } # Kayley Hodgkinson: Only showed up to training once or twice (AR)
  - { footyWebNumber: '03298293' } # Jacquiline Dornbierer: Only showed up to training once or twice (AR)
  - { footyWebNumber: '03256636' } # Kayla Saffron-Wilkins: Duplicate Kayla Wilkins '03143144' (AR)
  - { footyWebNumber: '03143522' } # Jaslyn Foster-davies: Duplicate Jaslyn Foster-Davies '03298371' (AR)
  - { footyWebNumber: '02934639' } # Jade O'Brien: Made it pretty clear she no longer wants to play (AR)
  - { footyWebNumber: '01601102' } # Renee Heenan: Debilitating injury (AR)
playerTeamExceptions: 
  - { code: U12B, footyWebNumber: '02892610' } # Thomas Walker: Playing up
