- registeredThisSeason: 
    - 2021 EFL Registration Fee
- registeredRecently: 
    - 2020 EFL Registration Fee
    - 2019 EFL Registration Fee
- productMap:
    - { from: Association - 2021 EFNL Registration fees - 2021 EFNL Junior Boys Registration fees, to: 2021 EFL Registration Fee }
    - { from: Association - 2021 EFNL Registration fees - 2021 EFNL Junior Girls Registration fees, to: 2021 EFL Registration Fee }
    - { from: Association - 2020 EFNL Registration Fee - 2020 EFNL Junior Boys Registration Fee, to: 2020 EFL Registration Fee }
    - { from: Association - 2020 EFNL Registration Fee - 2020 EFNL Junior Girls Registration Fee, to: 2020 EFL Registration Fee }
    - { from: Association - 2019 EFL Registration Fee - 2019 EFL Junior Girls Registration fee, to: 2019 EFL Registration Fee }
    - { from: Association - 2019 EFL Registration Fee - 2019 EFL Junior registration fee, to: 2019 EFL Registration Fee }
    - { from: Association - EFL Registration Fee - 2018 EFL Junior Registration Fee, to: 2018 EFL Registration Fee }
    - { from: Association - EFL Registration Fee - 2018 EFL Senior Registration Fee, to: 2018 EFL Registration Fee }
    - { from: Association - EFL Registration Fee - 2017 EFL Junior Registration Fee, to: 2017 EFL Registration Fee }
    - { from: Association - EFL Registration Fee - 2017 EFL Senior Registration Fee, to: 2017 EFL Registration Fee }
    - { from: Association - 2016 EFL Junior Registration Fee (inc GST), to: 2016 EFL Registration Fee }
    - { from: Association - 2015 EFL Junior Registration Fee (inc GST), to: 2015 EFL Registration Fee }
    - { from: Association - EFL Junior Registration Fee (inc GST), to: 2014 EFL Registration Fee }
    - { from: Club - 2020 Junior Club Fees, to: 2020 Club Fees }
    - { from: Club - 2020 Junior Club Fees (Revised), to: 2020 Club Fees (Revised) }
    - { from: Club - 2020 Junior Club Fees - deposit only, to: 2020 Club Fees (Deposit) }
    - { from: Club - 2020 Under 8 Club Fees, to: 2020 Club Fees (U8) }
    - { from: Club - 2020 Under 8 Club Fees (Revised), to: 2020 Club Fees (Revised) }
    - { from: Club - 2019 Junior Club Fees, to: 2019 Club Fees }
    - { from: Club - 2019 Junior Club Fees - deposit only, to: 2019 Club Fees (Deposit) }
    - { from: Club - 2019 Under 8 Club Fees, to: 2019 Club Fees (U8) }
    - { from: Club - 2018 Junior Club Fees, to: 2018 Club Fees }
    - { from: Club - 2018 Junior Club Fees - Payment No 1, to: 2018 Club Fees (1) }
    - { from: Club - 2018 Junior Club Fees - Payment No 3, to: 2018 Club Fees (3) }
    - { from: Club - 2018 Junior Club Fees - balance of fees, to: 2018 Club Fees (Balance) }
    - { from: Club - 2018 Junior Club Fees - deposit only, to: 2018 Club Fees (Deposit) }
    - { from: Club - 2017 Junior Club Fees, to: 2017 Club Fees }
